services:
  solver:
    restart: always
    build: .
    volumes:
      - "./:/usr/src/app"
    ports:
      - "5000:5000"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
